"""IngeTrazo entry point.

Free 3D modeler for architecture, civil engineering, and 3D printing.
Part of the IngePresupuestos ecosystem (modeling → quantity takeoff → budget).

Copyright (C) 2026 Marco Sumari Tellez and IngeTrazo contributors.
Licensed under GPL-3.0-or-later. See LICENSE.
"""
from __future__ import annotations

import sys
from pathlib import Path

from PySide6.QtCore import QLocale, QSettings
from PySide6.QtGui import QSurfaceFormat
from PySide6.QtWidgets import QApplication

from core import i18n


def _init_language() -> None:
    """Load the saved UI language, or default to the system locale.

    Reads the persisted choice from :class:`QSettings`; on first run, falls back
    to Spanish when the OS locale is Spanish, English otherwise.
    """
    saved = QSettings().value("language")
    if not saved:
        saved = "es" if QLocale.system().language() == QLocale.Spanish else "en"
    i18n.set_language(str(saved))

from views.main_window import MainWindow


def _configure_surface_format() -> None:
    """Request an OpenGL 3.3 Core context with an explicit 24-bit depth buffer.

    Without this, hidden-line removal silently degrades: some platforms hand
    QOpenGLWidget a context with no (or 16-bit) depth buffer, and faces stop
    occluding back-facing edges.
    """
    fmt = QSurfaceFormat()
    fmt.setVersion(3, 3)
    fmt.setProfile(QSurfaceFormat.CoreProfile)
    fmt.setDepthBufferSize(24)
    fmt.setStencilBufferSize(8)
    fmt.setSamples(4)  # 4× MSAA — smooths thin edge lines without hurting depth
    QSurfaceFormat.setDefaultFormat(fmt)


def main() -> int:
    _configure_surface_format()
    app = QApplication(sys.argv)
    app.setApplicationName("IngeTrazo")
    app.setOrganizationName("IngeTrazo")
    # Application icon (window title bar, task bar / dock). Generated by
    # scripts/gen_app_icon.py; the QIcon picks the right size per context.
    from PySide6.QtGui import QIcon
    icon = QIcon()
    icon_dir = Path(__file__).resolve().parent / "resources" / "icons"
    for size in (16, 32, 48, 64, 128, 256, 512):
        p = icon_dir / f"ingetrazo_{size}.png"
        if p.exists():
            icon.addFile(str(p))
    app.setWindowIcon(icon)
    _init_language()
    window = MainWindow()
    window.show()
    return app.exec()


if __name__ == "__main__":
    sys.exit(main())
