"""IngeTrazo entry point.

Free 3D modeler for architecture, civil engineering, and 3D printing.
Part of the IngePresupuestos ecosystem (modeling → quantity takeoff → budget).

Copyright (C) 2026 Marco Sumari Tellez and IngeTrazo contributors.
Licensed under GPL-3.0-or-later. See LICENSE.
"""
from __future__ import annotations

import sys
from pathlib import Path

# Native Wayland is the default. Known cosmetic tradeoff (2026-07-12): the
# compositor interleaves stale GL viewport frames under fast zoom bursts (a
# brief ghost/double image; flawless under XWayland, but XWayland degrades
# mixed-DPI multi-monitor setups — the audience's common rig). Escape hatch
# if the ghost bothers you: run with QT_QPA_PLATFORM=xcb. Re-test the ghost
# when Mutter/Qt update; no app-side workaround cured it (see CLAUDE.md).

from PySide6.QtCore import QLocale, QSettings
from PySide6.QtGui import QSurfaceFormat
from PySide6.QtWidgets import QApplication

from core import i18n


def _init_language() -> None:
    """Load the saved UI language, or default to the system locale.

    Reads the persisted choice from :class:`QSettings`; on first run, falls back
    to Spanish when the OS locale is Spanish, English otherwise.
    """
    saved = QSettings().value("language")
    if not saved:
        saved = "es" if QLocale.system().language() == QLocale.Spanish else "en"
    i18n.set_language(str(saved))

from views.main_window import MainWindow


def _configure_surface_format() -> None:
    """Request an OpenGL 3.3 Core context with an explicit 24-bit depth buffer.

    Without this, hidden-line removal silently degrades: some platforms hand
    QOpenGLWidget a context with no (or 16-bit) depth buffer, and faces stop
    occluding back-facing edges.
    """
    fmt = QSurfaceFormat()
    fmt.setVersion(3, 3)
    fmt.setProfile(QSurfaceFormat.CoreProfile)
    fmt.setDepthBufferSize(24)
    fmt.setStencilBufferSize(8)
    # NO setSamples here: MSAA lives in the viewport's offscreen scene FBO
    # (whose blit to the widget is the resolve). A multisampled widget/window
    # surface never antialiased the blitted scene, and its extra resolve step
    # interleaved stale frames on Wayland — the "ghost image" during fast zoom.
    QSurfaceFormat.setDefaultFormat(fmt)


def main() -> int:
    _configure_surface_format()
    app = QApplication(sys.argv)
    app.setApplicationName("IngeTrazo")
    app.setOrganizationName("IngeTrazo")
    # Application icon (window title bar, task bar / dock). Generated by
    # scripts/gen_app_icon.py; the QIcon picks the right size per context.
    from PySide6.QtGui import QIcon
    icon = QIcon()
    icon_dir = Path(__file__).resolve().parent / "resources" / "icons"
    for size in (16, 32, 48, 64, 128, 256, 512):
        p = icon_dir / f"ingetrazo_{size}.png"
        if p.exists():
            icon.addFile(str(p))
    app.setWindowIcon(icon)
    # Wayland matches the running window to its .desktop entry (and thus the
    # dock icon) by this name — see scripts/install_desktop.sh.
    app.setDesktopFileName("ingetrazo")
    _init_language()
    window = MainWindow()
    # A document passed on the command line (the OS file association's
    # double-click on Windows/Linux hands it as argv[1]) opens right away.
    # .igz opens as the document; a double-clicked .skp imports through the
    # native openskp backend AFTER the first paint (big models parse for
    # seconds — the window must be visible, not frozen pre-show).
    if len(sys.argv) > 1:
        doc = Path(sys.argv[1])
        if doc.exists():
            ext = doc.suffix.lower()
            if ext == ".igz":
                window.open_path(doc)
            elif ext == ".skp":
                from PySide6.QtCore import QTimer

                def _open_skp():
                    if window.import_skp_path(doc):
                        # Frame the model — a double-clicked import often sits
                        # far from the origin (geolocated models), so land the
                        # camera on it instead of on empty space.
                        if hasattr(window, "_on_zoom_extents"):
                            window._on_zoom_extents()

                QTimer.singleShot(0, _open_skp)
    window.show()
    return app.exec()


if __name__ == "__main__":
    sys.exit(main())
